language: python
python:
  - 3.6

before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin

install:
  - pip install pipenv
  - pipenv install

script:
  - ./ci/run_changed_spiders.sh
