name: Weekly Spider Run

on:
  schedule:
    - cron: "0 5 * * MON"
  workflow_dispatch:

jobs:
  spider:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: 3.9

      - name: Install pipenv
        run: |
          pip --quiet install pipenv

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pipenv --bare install --system --deploy
          sudo apt-get install -y jq
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Run all spiders
        env:
          GITHUB_TOKEN: ${{ secrets.SCRAPERBOT_GITHUB_TOKEN }}
          GITHUB_WORKSPACE: "/tmp"
          S3_BUCKET: "placescraper-results"
        run: ./ci/run_all_spiders.sh
